### ISSUE TITLE
"type": "missing", "msg": "Field required"

### ISSUE THREAD

**Issue by abdulsittar** [smnmnkr/TWON-Recommender#1]
![Uploading Screenshot 2024-03-13 112943.png…]()

**Comment by simon-muenker** [comment]
Thanks for reporting the issue. Please provide your input and expected output as a description. 
@abdulsittar It looks like the image uploaded did not work.

**Comment by abdulsittar** [comment]
Thanks for replying. Following is the description:
Input:
items: [{"comments": [],"dislikes": ["2024-02-23T19:13:15.991751", "2024-02-24T11:13:15.991752"],      "id": "P0001", "likes": ["2024-02-22T15:13:15.991748",    "2024-02-23T17:13:15.991750"],  "timestamp": "2024-02-22T11:13:15.991730"}]
reference_datetime: 2024-02-25T11:13:15.999949
decay: {"minimum": 0.2,"reference_timedelta": "P3D"}
noise: {"low": 0.6, "high": 1.4}
engagement: {"func": "count_based","log_normalize": false}
weights: {"likes": 1,"dislikes": 1,"comments": 1,"comments_likes": 1,"comments_dislikes": 1}
id: 3fa85f64-5717-4562-b3fc-2c963f66afa6

Output:
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.6/v/missing"
        }
    ]
}
![Screenshot 2024-03-13 112943](https://github.com/smnmnkr/TWON-Ranker/assets/6714960/3e19ff71-65e3-41e3-865e-9ec36822346d)

**Comment by simon-muenker** [comment]
I see your problem. While using Postman as an API client, you cannot send nested objects through the form-data interface in this way. For the correct formulation of nested objects, see [this thread.](https://community.postman.com/t/create-nested-array-with-json-object-with-form-data/15187) However, I would advise sending the post request using raw input. I attached a screenshot below with this solution and the successful response. The ranking map in the response is highlighted green.
![rank-post-request](https://github.com/smnmnkr/TWON-Ranker/assets/56649035/62522fc5-fd22-4db9-837b-11042f111ef5)

**Comment by abdulsittar** [comment]
Thanks for mentioning the issue. Can you please share the output of this request as well?

**Comment by abdulsittar** [comment]
Oh I see. You mean the bordered green is the ranking map which is the output of the request call?

**Comment by simon-muenker** [comment]
Correct, the body of the request-response contains the key "ranking_map". It is a dictionary that contains the post IDs with the calculated ranking scores. Higher values mean a higher ranking. Please confirm if this is clear and if you can replicate the results. I will close the issue, and when the time allows, I will extend the documentation.

**Comment by abdulsittar** [comment]
Can you please have a look at the attached .json file and tell me what's is missing in it. or perhaps would be better if you could try running ranker on this json file your end and share the response with me.
[test (2).json](https://github.com/smnmnkr/TWON-Ranker/files/14614638/test.2.json)

**Comment by simon-muenker** [comment]
Thanks for submitting the examples JSON file. Based on the file, I see two issues. The comments are missing their IDs. Please provide a unique identifier for each comment of a post. Also, the list of comments contains null values for some cases. Before sending a request, please sanitize the list of comments and remove null entries. I attached both screenshots highlighting the issues.
![missing_comment_id](https://github.com/smnmnkr/TWON-Ranker/assets/56649035/0752c395-efdf-4346-97f7-6cc589b324a2)
![null_comments](https://github.com/smnmnkr/TWON-Ranker/assets/56649035/0bc2fd3f-cdc9-4b24-a030-cd12dd97a4ab)

**Comment by abdulsittar** [comment]
Hi Simon, Thanks for you time. Yes it is fixed now. 

If I need more collaboration then will let you know.
